### ISSUE TITLE
simplify trait bounds

### ISSUE THREAD

**Issue by Jianqoq** [Jianqoq/Hpt#13]
currently our trait bounds are complicated and there are a lot of unececessary bounds included

### Tasks
- [x] add bounds to CommonBounds
- [x] implment methods for complex number
- [x] Remove all unececessary bounds
- [x] Tests passed
